packages:
  - packages/*
  - examples/*
allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  json-editor-vue: true
  simple-git-hooks: true
  vue-demi: true
overrides:
  '@rollup/plugin-terser>serialize-javascript': ^7.0.7
  '@surma/rollup-plugin-off-main-thread>ejs': ^3.1.10
  'config-chain>ini': ^1.3.8
  'workbox-build': ^7.4.1
  'workbox-build>glob': ^11.1.0
